FROM fedora-base

ARG SODA_VERSION
ARG SODA_SOURCE_REVISION
ARG SOURCE_DATE_EPOCH
ARG SODA_CREATED
ARG FEDORA_BASE_REFERENCE
ARG BOOTC_NEVRA

LABEL org.opencontainers.image.title="Soda OS" \
      org.opencontainers.image.description="Soda OS remote development appliance" \
      org.opencontainers.image.source="https://github.com/LevitateOS/soda-os" \
      org.opencontainers.image.version="${SODA_VERSION}" \
      org.opencontainers.image.revision="${SODA_SOURCE_REVISION}" \
      org.opencontainers.image.created="${SODA_CREATED}" \
      org.opencontainers.image.base.name="${FEDORA_BASE_REFERENCE}" \
      org.sodaos.source-date-epoch="${SOURCE_DATE_EPOCH}"

COPY --from=rpm-inputs /soda-release-*.rpm /var/tmp/soda-rpms/
COPY --from=rpm-inputs /soda-runtime-*.rpm /var/tmp/soda-rpms/
COPY --from=rpm-inputs /soda-projects-*.rpm /var/tmp/soda-rpms/
COPY --from=rpm-inputs /soda-forgejo-*.rpm /var/tmp/soda-rpms/
COPY --from=rpm-inputs /soda-bun-*.rpm /var/tmp/soda-rpms/
COPY --from=rpm-inputs /soda-tea-*.rpm /var/tmp/soda-rpms/
COPY --from=lock-inputs /fedora-packages.txt /var/tmp/soda-lock/fedora-packages.txt
COPY --from=lock-inputs /expected-packages.txt /var/tmp/soda-lock/expected-packages.txt

RUN dnf -y --setopt=install_weak_deps=False --enablerepo=updates-testing install \
      $(cat /var/tmp/soda-lock/fedora-packages.txt) \
      /var/tmp/soda-rpms/*.rpm \
    && dnf -y remove avahi \
    && ! rpm -q avahi \
    && ! test -e /usr/lib/systemd/system/avahi-daemon.service \
    && dnf clean all \
    && rm -rf \
      /usr/lib/sysimage/libdnf5/transaction_history.sqlite* \
      /var/cache/dnf \
      /var/cache/libdnf5 \
      /var/cache/ldconfig/aux-cache \
      /var/lib/dnf/repos \
      /var/log/dnf5.log \
      /run/dnf \
      /var/tmp/soda-rpms \
    && systemd-sysusers /usr/lib/sysusers.d/soda-projects.conf /usr/lib/sysusers.d/forgejo.conf \
    && checkmodule -M -m -o /run/soda_forgejo_shadow.mod /usr/share/soda/selinux/soda-forgejo-shadow.te \
    && semodule_package -o /run/soda_forgejo_shadow.pp -m /run/soda_forgejo_shadow.mod \
    && semodule -i /run/soda_forgejo_shadow.pp \
    && semodule -l | grep -Fx soda_forgejo_shadow \
    && rm -f /run/soda_forgejo_shadow.mod /run/soda_forgejo_shadow.pp \
    && systemd-tmpfiles --create /usr/lib/tmpfiles.d/forgejo.conf \
    && getent group soda-workspaces \
    && getent group soda-forgejo-shadow \
    && test "$(stat -c '%U:%G:%a' /etc/shadow)" = root:soda-forgejo-shadow:40 \
    && grep -Fx 'SupplementaryGroups=soda-forgejo-shadow' /usr/lib/systemd/system/forgejo.service \
    && install -o root -g root -m 0644 /usr/lib/soda/pam/cockpit /etc/pam.d/cockpit \
    && restorecon -F /etc/pam.d/cockpit \
    && systemctl preset sshd.service soda-tailscale-enroll.service cockpit.socket forgejo.service tailscaled.service nftables.service \
    && systemctl enable sshd.service cockpit.socket forgejo.service tailscaled.service nftables.service \
    && getent passwd git \
    && systemctl mask bootc-fetch-apply-updates.timer \
    && cp -f /usr/lib/soda/os-release /etc/os-release \
    && cp -f /usr/lib/soda/os-release /usr/lib/os-release \
    && cp -f /usr/lib/soda/issue /etc/issue \
    && cp -f /usr/lib/soda/issue /etc/issue.net \
    && cp -f /usr/lib/soda/system-release /etc/system-release \
    && rm -f /etc/redhat-release \
    && semanage fcontext -a -t var_lib_t '/var/lib/soda(/.*)?' \
    && semanage fcontext -a -t ssh_home_t '/var/lib/forgejo/.ssh(/.*)?' \
    && restorecon -RF /var/lib/forgejo/.ssh \
    && ssh-keygen -q -t ed25519 -N '' -f /run/soda-sshd-hostkey \
    && /usr/sbin/sshd -t -h /run/soda-sshd-hostkey \
    && rm -f /run/soda-sshd-hostkey /run/soda-sshd-hostkey.pub \
    && test "$(rpm -q --qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}' bootc)" = "${BOOTC_NEVRA}" \
    && bootc switch --help | grep -F -- '--download-only' \
    && bootc switch --help | grep -F -- '--from-downloaded' \
    && test -r /usr/share/soda/toolset-commands.txt \
    && while IFS= read -r command; do command -v "$command" >/dev/null; done < /usr/share/soda/toolset-commands.txt \
    && install -d -m 0755 /usr/share/soda \
    && rpm -qa --qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}\n' | LC_ALL=C sort > /usr/share/soda/rpm-inventory.txt \
    && while IFS= read -r package; do grep -Fqx "$package" /usr/share/soda/rpm-inventory.txt; done < /var/tmp/soda-lock/expected-packages.txt \
    && cd /usr/share/soda \
    && sha256sum rpm-inventory.txt > rpm-inventory.sha256 \
    && sha256sum --check rpm-inventory.sha256 \
    && rm -rf /var/tmp/soda-lock
