FROM quay.io/fedora/fedora-bootc@sha256:85677d47c03b2e1f8f9a3a19d838023ea154229817d579d4b4da5b87a21c9c1a

ARG SODA_VERSION
ARG SODA_SOURCE_REVISION
ARG SOURCE_DATE_EPOCH
ARG SODA_CREATED

LABEL org.opencontainers.image.title="Soda OS" \
      org.opencontainers.image.description="Soda OS remote development appliance" \
      org.opencontainers.image.source="https://github.com/LevitateOS/soda-os" \
      org.opencontainers.image.version="${SODA_VERSION}" \
      org.opencontainers.image.revision="${SODA_SOURCE_REVISION}" \
      org.opencontainers.image.created="${SODA_CREATED}" \
      org.opencontainers.image.base.name="quay.io/fedora/fedora-bootc@sha256:85677d47c03b2e1f8f9a3a19d838023ea154229817d579d4b4da5b87a21c9c1a" \
      org.sodaos.state-schema="2" \
      org.sodaos.source-date-epoch="${SOURCE_DATE_EPOCH}"

COPY .artifacts/rpms/soda-release-*.rpm /var/tmp/soda-rpms/
COPY .artifacts/rpms/soda-runtime-*.rpm /var/tmp/soda-rpms/
COPY .artifacts/rpms/soda-cockpit-*.rpm /var/tmp/soda-rpms/
COPY .artifacts/bootc/fedora-packages.txt /var/tmp/soda-lock/fedora-packages.txt
COPY .artifacts/bootc/expected-packages.txt /var/tmp/soda-lock/expected-packages.txt
COPY .artifacts/bootc/trust/registry-ca.crt /usr/share/pki/ca-trust-source/anchors/soda-registry-ca.crt
COPY .artifacts/bootc/trust/cosign.pub /usr/share/soda/release/cosign.pub
COPY packaging/release/policy.json /etc/containers/policy.json
COPY packaging/release/registries.d.yaml /etc/containers/registries.d/soda.yaml

RUN dnf -y --setopt=install_weak_deps=False --enablerepo=updates-testing install \
      $(cat /var/tmp/soda-lock/fedora-packages.txt) \
      /var/tmp/soda-rpms/*.rpm \
    && dnf clean all \
    && rm -rf \
      /usr/lib/sysimage/libdnf5/transaction_history.sqlite* \
      /var/cache/dnf \
      /var/cache/libdnf5 \
      /var/cache/ldconfig/aux-cache \
      /var/lib/dnf/repos \
      /var/log/dnf5.log \
      /run/dnf \
      /var/tmp/soda-rpms \
    && systemd-sysusers /usr/lib/sysusers.d/soda.conf \
    && test "$(getent group soda-api | cut -d: -f3)" = 976 \
    && test "$(id -u soda-cockpit)" = 976 \
    && install -d -m 0755 /opt/soda/toolchains \
    && systemctl preset sshd.service sodad.service soda-authd.service soda-cockpit.service avahi-daemon.service var-srv-soda-projects.mount opt-soda-toolchains.mount \
    && systemctl enable sshd.service sodad.service soda-authd.service soda-cockpit.service avahi-daemon.service var-srv-soda-projects.mount opt-soda-toolchains.mount \
    && systemctl mask bootc-fetch-apply-updates.timer \
    && cp -f /usr/lib/soda/os-release /etc/os-release \
    && cp -f /usr/lib/soda/os-release /usr/lib/os-release \
    && cp -f /usr/lib/soda/issue /etc/issue \
    && cp -f /usr/lib/soda/issue /etc/issue.net \
    && cp -f /usr/lib/soda/system-release /etc/system-release \
    && cp -f /usr/lib/soda/system-release /etc/redhat-release \
    && semanage fcontext -a -t var_lib_t '/var/lib/soda(/.*)?' \
    && semanage fcontext -a -e /home /var/lib/soda/projects \
    && semanage fcontext -a -e /opt /var/lib/soda/toolchains \
    && semanage fcontext -a -e /home /var/srv/soda/projects \
    && semanage fcontext -a -e /opt /opt/soda/toolchains \
    && semanage fcontext -a -t var_log_t '/var/log/soda(/.*)?' \
    && semanage fcontext -a -t ssh_home_t '/etc/soda/authorized_keys(/.*)?' \
    && restorecon -RF /etc/soda/authorized_keys /opt/soda/toolchains \
    && ssh-keygen -q -t ed25519 -N '' -f /run/soda-sshd-hostkey \
    && /usr/sbin/sshd -t -h /run/soda-sshd-hostkey \
    && rm -f /run/soda-sshd-hostkey /run/soda-sshd-hostkey.pub \
    && test "$(rpm -q --qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}' bootc)" = "bootc-0:1.16.10-1.fc44.aarch64" \
    && rpm -q skopeo \
    && /usr/libexec/soda/cosign version | grep -F 'GitVersion:    v3.1.2' \
    && bootc switch --help | grep -F -- '--download-only' \
    && bootc switch --help | grep -F -- '--from-downloaded' \
    && update-ca-trust extract \
    && install -d -m 0755 /usr/share/soda \
    && rpm -qa --qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}\n' | LC_ALL=C sort > /usr/share/soda/rpm-inventory.txt \
    && while IFS= read -r package; do grep -Fqx "$package" /usr/share/soda/rpm-inventory.txt; done < /var/tmp/soda-lock/expected-packages.txt \
    && cd /usr/share/soda \
    && sha256sum rpm-inventory.txt > rpm-inventory.sha256 \
    && sha256sum --check rpm-inventory.sha256 \
    && rm -rf /var/tmp/soda-lock
