schema_version = 1

[architecture]
name = "aarch64"
oci = "arm64"
platform = "linux/arm64"
artifact = "aarch64"
installer = "aarch64"

[base]
reference = "quay.io/fedora/fedora-bootc@sha256:950a52fa1244db4d7fe2673af57fd6784a605a83bec3cd2d716ed8c00ebd366d"
archive = "distro/base/fedora-bootc-44-aarch64/Fedora-bootc-44.20260829.0-aarch64.oci-archive.tar"
archive_sha256 = "6805e85fda436c1afd8f9c540a05f5028982b44b965ae1ff6ca249702a328c7d"
bootc_nevra = "bootc-0:1.16.10-1.fc44.aarch64"
runtime_package_lock = "distro/locks/runtime-packages-aarch64.toml"

[builder]
base_reference = "registry.fedoraproject.org/fedora@sha256:9c8b291e256262b91aac5b3da50ea323760d0a6b449c6d6ad5f01d9550d48d2a"
package_lock = "distro/locks/builder-packages-aarch64.toml"
go_archive = ".artifacts/tools/go1.27.0.linux-arm64.tar.gz"
go_archive_sha256 = "51798d2c42d0e1c6ed7fd9f48728b4193abac9e8aad6dbac2fe96a81f5909bda"

[installer]
package_lock = "distro/locks/installer-packages-aarch64.toml"
tool_lock = "distro/locks/installer-image-builder-aarch64.toml"
iso_config = "packaging/installer/iso-aarch64.yaml"

[release]
channel = "aarch64"
