schema_version = 1

[architecture]
name = "x86_64"
oci = "amd64"
platform = "linux/amd64"
artifact = "x86_64"
installer = "x86_64"

[base]
reference = "quay.io/fedora/fedora-bootc@sha256:7b7db1d22fe0291fa7e05bc6aeece054b51be5f4857a8ecdb1e69cd368e129d6"
archive = "distro/base/fedora-bootc-44-x86_64/Fedora-bootc-44.20260828.0-x86_64.oci-archive.tar"
archive_sha256 = "22fae049e1bb15f14310600544e2b6ad41e08d3b15f89676ed44dd3ad52c3f10"
bootc_nevra = "bootc-0:1.16.10-1.fc44.x86_64"
runtime_package_lock = "distro/locks/runtime-packages-x86_64.toml"

[builder]
base_reference = "registry.fedoraproject.org/fedora@sha256:459d2bd81d249a52f7d4be6ffaeeb9fbad795501cdbe7be207c0745f5ad7de66"
package_lock = "distro/locks/builder-packages-x86_64.toml"

[cosign]
architecture = "amd64"
sha256 = "f7622ed3cf22e55e1ae6377c080979ff77a22da9981c11df222a2e444991e7cf"

[installer]
package_lock = "distro/locks/installer-packages-x86_64.toml"
tool_lock = "distro/locks/installer-image-builder-x86_64.toml"
iso_config = "packaging/installer/iso-x86_64.yaml"

[release]
channel = "x86_64"
