schema_version = 1
architecture = "x86_64"
oci_architecture = "amd64"
oci_platform = "linux/amd64"
artifact_architecture = "x86_64"
installer_architecture = "x86_64"
base_reference = "quay.io/fedora/fedora-bootc@sha256:7b7db1d22fe0291fa7e05bc6aeece054b51be5f4857a8ecdb1e69cd368e129d6"
base_archive = "distro/base/fedora-bootc-44-x86_64/Fedora-bootc-44.20260828.0-x86_64.oci-archive.tar"
base_archive_sha256 = "22fae049e1bb15f14310600544e2b6ad41e08d3b15f89676ed44dd3ad52c3f10"
bootc_nevra = "bootc-0:1.16.10-1.fc44.x86_64"
runtime_package_lock = "distro/locks/runtime-packages-x86_64.toml"
builder_base_reference = "registry.fedoraproject.org/fedora@sha256:459d2bd81d249a52f7d4be6ffaeeb9fbad795501cdbe7be207c0745f5ad7de66"
builder_package_lock = "distro/locks/builder-packages-x86_64.toml"
target_cosign_architecture = "amd64"
target_cosign_sha256 = "f7622ed3cf22e55e1ae6377c080979ff77a22da9981c11df222a2e444991e7cf"
installer_package_lock = "distro/locks/installer-packages-x86_64.toml"
installer_tool_lock = "distro/locks/installer-image-builder-x86_64.toml"
release_channel = "x86_64"
