FROM fedora-base

# This image exists only while constructing installer media. It is not a Soda
# runtime image and is never published as a Soda release.
COPY .artifacts/installer/context/installer-packages.txt /usr/share/soda-installer/packages.txt
COPY .artifacts/installer/context/installer-boot-packages.txt /usr/share/soda-installer/boot-packages.txt
COPY .artifacts/installer/context/installer-efi-vendor.txt /usr/share/soda-installer/efi-vendor.txt

RUN dnf -y install --setopt=install_weak_deps=False \
      $(cat /usr/share/soda-installer/packages.txt) \
    && dnf clean all \
    && test "$(find /usr/lib/modules -mindepth 1 -maxdepth 1 -type d | wc -l)" -eq 1 \
    && test "$(find /usr/lib/efi/shim -mindepth 3 -maxdepth 3 -type d ! -name BOOT | wc -l)" -eq 1 \
    && rpm -q $(cat /usr/share/soda-installer/boot-packages.txt) \
    && test -f /usr/lib/grub/i386-pc/boot_hybrid.img

RUN mkdir -p /boot/efi /usr/lib/image-builder/bootc /usr/lib/systemd/logind.conf.d \
    && mkdir -p "$(realpath /root)" \
    && cp -ra /usr/lib/efi/*/*/EFI /boot/efi \
    && echo "install:x:0:0:root:/root:/usr/libexec/anaconda/run-anaconda" >> /etc/passwd \
    && echo "install::14438:0:99999:7:::" >> /etc/shadow \
    && passwd -d root \
    && mv /usr/share/anaconda/list-harddrives-stub /usr/bin/list-harddrives \
    && mv /etc/yum.repos.d /etc/anaconda.repos.d \
    && ln -sf /lib/systemd/system/anaconda.target /etc/systemd/system/default.target \
    && rm -f /usr/lib/systemd/system-generators/systemd-gpt-auto-generator \
    && ln -sf /usr/lib/systemd/system/anaconda-shell@.service /usr/lib/systemd/system/autovt@.service \
    && mkdir -p /etc/systemd/user/pipewire.service.d /etc/systemd/user/pipewire.socket.d

COPY .artifacts/installer/context/interactive-defaults.ks /usr/share/anaconda/interactive-defaults.ks
COPY packaging/installer/soda-storage.conf /etc/anaconda/conf.d/90-soda-storage.conf
COPY .artifacts/installer/context/iso.yaml /usr/lib/image-builder/bootc/iso.yaml
COPY packaging/installer/anaconda-shell.conf /usr/lib/systemd/logind.conf.d/anaconda-shell.conf
COPY packaging/installer/pipewire-allow-root.conf /etc/systemd/user/pipewire.service.d/allowroot.conf
COPY packaging/installer/pipewire-allow-root.conf /etc/systemd/user/pipewire.socket.d/allowroot.conf

RUN kernel="$(find /usr/lib/modules -mindepth 2 -maxdepth 2 -name vmlinuz -printf '%h\n' | sed 's#.*/##')" \
    && test -n "$kernel" \
    && DRACUT_NO_XATTR=1 dracut --force --zstd --reproducible --no-hostonly \
         --add anaconda "/usr/lib/modules/${kernel}/initramfs.img" "$kernel" \
    && test -f "/usr/lib/modules/${kernel}/initramfs.img"
