#!/bin/sh
set -eu

template=/usr/share/soda/forgejo/app.ini.tmpl
target=/etc/forgejo/app.ini

if [ -e "$target" ]; then
  exit 0
fi

install -d -m 0750 -o root -g forgejo /etc/forgejo
umask 077
internal_token=$(forgejo generate secret INTERNAL_TOKEN)
jwt_secret=$(forgejo generate secret JWT_SECRET)
lfs_jwt_secret=$(forgejo generate secret LFS_JWT_SECRET)
secret_key=$(forgejo generate secret SECRET_KEY)
sed \
  -e "s/@INTERNAL_TOKEN@/${internal_token}/g" \
  -e "s/@JWT_SECRET@/${jwt_secret}/g" \
  -e "s/@LFS_JWT_SECRET@/${lfs_jwt_secret}/g" \
  -e "s/@SECRET_KEY@/${secret_key}/g" \
  "$template" > "$target.tmp"
chown root:forgejo "$target.tmp"
chmod 0640 "$target.tmp"
mv "$target.tmp" "$target"
