# Anaconda profile for the Soda OS development appliance.

[Profile]
profile_id = sodaos
base_profile = rocky

[Profile Detection]
os_id = sodaos

[Anaconda]
forbidden_modules =
    org.fedoraproject.Anaconda.Modules.Subscription

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = rocky
menu_auto_hide = True

[Storage]
file_system_type = xfs
default_scheme = LVM
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    /home (min 500 MiB, free 50 GiB)
    swap

[Storage Constraints]
swap_is_recommended = True

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/soda.css
hidden_spokes =
    LangsupportSpoke
    SourceSpoke
    SoftwareSelectionSpoke
    KdumpSpoke
    PasswordSpoke
    CustomPartitioningSpoke
    BlivetGuiSpoke
    FilterSpoke
can_change_root = False
can_change_users = True
password_policies =
    root (quality 1, length 6)
    user (quality 1, length 6)
    luks (quality 1, length 6)
show_kernel_options = False

[License]
eula =

[Timezone]
geolocation_provider =

[Localization]
use_geolocation = False
