ARG BUILDER_BASE_REFERENCE
FROM ${BUILDER_BASE_REFERENCE}

COPY .artifacts/builder/packages.lock /usr/share/soda-builder/packages.lock

RUN dnf -y install --setopt=install_weak_deps=False $(awk -F '"' '/^nevra = / { print $2 }' /usr/share/soda-builder/packages.lock) \
    && actual="$(rpm -qa --qf '%{NAME}-%{EPOCHNUM}:%{VERSION}-%{RELEASE}.%{ARCH}\n' | LC_ALL=C sort | sha256sum | awk '{print $1}')" \
    && expected="$(awk -F '"' '/^inventory_sha256 = / { print $2 }' /usr/share/soda-builder/packages.lock)" \
    && test "$actual" = "$expected" \
    && dnf clean all

ENV GOTOOLCHAIN=local

WORKDIR /src
